Rgpd suppression comptes candidats
anct-cnum/api-conseiller-numerique pull request #1208
Opened 2023-07-19 09:13 UTC by MorganP-projects

2023-07-19 11:40 UTC, squirrion commented on src/tools/scripts/archived/cras-ajout-key-structure.js
Dans les required des 2 fichiers renommés, pas besoin d'adapter des appels ? (genre ./utils)

2023-07-19 11:41 UTC, squirrion commented on src/tools/scripts/suppressionInactifsComptes.js
> +              { 'contact.inactivite': true, 'userCreated': false, 'updatedAt': new Date() }
normal ? si on fait ca ca veut dire qu'il faut updater côté PG ?

2023-07-19 11:43 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +      }
normalement pas besoin non ? Le script des comptes inactifs devrait faire le taff au moment voulu et positionner le flag

2023-07-19 11:44 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +    const candidatASupprimer = anonymisationCandidat(candidatInactif);
ok y avait pas une fonction générique qui faisait le travail côté espace candidat ?

2023-07-19 11:45 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return;
Y avait pas un envoi de mail à PIX ?

2023-07-19 12:27 UTC, MorganP-projects commented on src/tools/scripts/rgpd-suppression-compte.js
> +      }
Il n'y a qu'un seul compte en prod qui se retrouve flagué avec inactivite, donc je double sécurise :D

2023-07-19 12:41 UTC, MorganP-projects commented on src/tools/scripts/archived/cras-ajout-key-structure.js
Ils sont archivés pour le coup, même si github parle de File renamed :)

2023-07-19 13:06 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +      }
Normalement 0, le script est désactivé en prod (parametres de rétention à 0 car c'était trop dangereux pour le ménage structures avant la migration)
Concernant cette partie, du $or, ca ne devrait pas arriver car seul les conseillers avec le flag inactivité a vu son compte user supprimé.

2023-07-19 13:07 UTC, squirrion commented on src/tools/scripts/suppressionInactifsComptes.js
> +              { 'contact.inactivite': true, 'userCreated': false, 'updatedAt': new Date() }
Nop car on ne positionne que le flag inactivite. Qui n'existe pas côté PG (pas dans la synchro)

2023-07-19 14:29 UTC, MorganP-projects commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await db.collection('misesEnRelation').updateMany({
Ok !

2023-07-20 12:11 UTC, squirrion commented on clevercloud/cron.json
> +  "0 3 * * * $ROOT/src/tools/jobs/rgpd-delete-accounts.sh",
Juste pour qu'on s'en souvienne avec le lien avec le CRON du dessus
```suggestion
  "0 3 * * * $ROOT/src/tools/jobs/delete-inactive-candidats.sh",
```

2023-07-20 12:13 UTC, squirrion commented on src/tools/scripts/suppressionInactifsComptes.js
> +            await db.collection('structures').updateOne({ _id: userStructure.entity.oid }, { $set:
du coup je pense que tu peux rollback les modifis de ce fichier

2023-07-20 12:14 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +    ]
```suggestion
      {  inactivite: true  }
    ]
```

2023-07-20 12:17 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await pool.query(`DELETE FROM djapp_matching WHERE coach_id = $1`, [candidatInactif.idPG]);
cette table n'est pas utilisé côté PG je crois cc @jystervinou

2023-07-20 15:10 UTC, MorganP-projects commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await pool.query(`DELETE FROM djapp_matching WHERE coach_id = $1`, [candidatInactif.idPG]);
En tout cas je l'ai récupéré du process de suppression d'un candidat :D

2023-07-20 17:09 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await pool.query(`DELETE FROM djapp_matching WHERE coach_id = $1`, [candidatInactif.idPG]);
ah oui pas utilisé mais doit y avoir un pb si il reste des choses dans cette table avec les jointures

2023-07-21 11:49 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await pool.query(`DELETE FROM djapp_matching WHERE coach_id = $1`, [candidatInactif.idPG]);
Ah je ne me suis mal exprimé, cette table est pas utilisé mais effectivement si il y a une data dedans la suppression va échouer à cause des clés étrangères

2023-07-21 11:50 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +  await pool.query(`DELETE FROM djapp_matching WHERE coach_id = $1`, [candidatInactif.idPG]);
Du coup vaut mieux laisser la requete :sweat_smile:

2023-07-24 11:46 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          await candidatSupprimeEmailPix(db, app)(candidatInactif);
candidatInactif ici normal ? les infos dans le mail ne seront pas perdus ? (nom prénom email ?)

2023-07-24 11:46 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          await deleteMailSib(app)(candidatInactif.email);
candidatInactif.email n'existe pas non ?

2023-07-25 15:44 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          await candidatSupprimeEmailPix(db, app)(candidatInactif);
Ah oui oula j'étais pas réveillé

2023-07-25 15:44 UTC, squirrion approved these changes

2023-07-25 15:46 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
s'il y a des datas dans djapp_matching ca va pas crashé le deleteCandidatInactif ?

2023-07-26 08:51 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
Yes apparemment c'était bien inversé dans la fonction suppressionTotalCandidat. Je ne sais pas si on pouvait pas utilisé directement les fonctions existants suppressionTotalCandidat & archiverLaSuppression

2023-07-26 08:51 UTC, squirrion requested changes
Dernier comm

2023-08-02 09:21 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
On pouvait pas utilisé les fonctions suppressionTotalCandidat & archiverLaSuppression ? Comme ce qui est fait avec l'appel à suppressionCv, deleteMailSib

2023-08-02 13:18 UTC, MorganP-projects commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
Je viens de tester et non, le passage de l'app ne lui convient pas (je ne peux pas testé en local j'ai un problème d'authentification)

`info: password authentication failed for user "prioux" {"length":102,"name":"error","severity":"FATAL","code":"28P01","file":"auth.c","line":"330","routine":"auth_failed"}
error: app.get(...).captureException is not a function
`

2023-08-02 14:34 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
ah bizarre, pourtant on doit faire appel à app dans le execute dans d'autres scripts

2023-08-03 10:09 UTC, squirrion commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
@MorganP-projects Ok c'est parce qu'il faudrait passer Sentry et app en paramètres dans les 2 fonctions utilitaires

2023-08-03 12:51 UTC, MorganP-projects commented on src/tools/scripts/rgpd-suppression-compte.js
> +          return await deleteMeRCandidatInactif(db)(candidatASupprimer);
Je n'ai plus de message d'erreur mais j'ai toujours l'info :
`info: password authentication failed for user "prioux" {"length":102,"name":"error","severity":"FATAL","code":"28P01","file":"auth.c","line":"330","routine":"auth_failed"}
`
Cf: mon nouveau commit

2023-08-03 14:39 UTC, squirrion approved these changes

2023-08-03 14:40 UTC, merged