ajout de condition lié au process fin de contrat naturel script PQR
anct-cnum/api-conseiller-numerique pull request #1241
Opened 2023-09-12 12:13 UTC by QuentinFontenay

2023-09-12 12:58 UTC, squirrion commented on src/tools/exports/liste-cnfs-pour-carto.js
> +          'conseillerObj.nonAffichageCarto': { $ne: true },
yes à voir si conseillerObj bien à jour

2023-09-12 13:05 UTC, squirrion approved these changes

2023-09-12 13:45 UTC, jystervinou commented on src/tools/exports/liste-cnfs-pour-carto.js
> +          'conseillerObj.nonAffichageCarto': { $ne: true },
@squirrion script de @Ornella452 à lancer ?

2023-09-12 13:47 UTC, jystervinou approved these changes

2023-09-14 08:13 UTC, squirrion commented on src/tools/exports/liste-cnfs-pour-carto.js
> +          'conseillerObj.nonAffichageCarto': { $ne: true },
yes ca serait bien juste avant pour être tranquille

2023-09-18 07:23 UTC, squirrion requested changes
Rétropédalage suites retours ANCT
On ne remonterait plus les mêmes informations et peut-être qu'on remonterait même les CN en fin de contrat

2023-09-27 20:17 UTC, jystervinou commented
@squirrion @QuentinFontenay à fermer

2023-09-27 21:50 UTC, closed without merging

2023-09-27 21:50 UTC, squirrion commented
Fermé