Email candidat pix non partage
anct-cnum/api-conseiller-numerique pull request #190
Opened 2021-05-21 09:38 UTC by MorganP-projects

2021-05-21 09:48 UTC, loicguillois commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +function removeAccentsRegex(string = '') {
c'est cool ! il faudra qu'on déplace ça dans un fichier `utils` par exemple avec quelques tests unitaires.

2021-05-21 09:52 UTC, loicguillois commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +    //const email = reply['Adresse email'];
commentaire à supprimer

2021-05-21 09:52 UTC, loicguillois commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +    //logger.info(nom + ' ' + prenom + ' ' + partage + ' ' + pourcentage);
commentaire à supprimer

2021-05-21 09:52 UTC, loicguillois commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +        await pixUser({
avec ES6 quand la clef et la valeur on le même nom tu peux faire ça :

```
        await pixUser({
          nom
          prenom
          id
        });
```

2021-05-21 09:52 UTC, loicguillois commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +    logger.info(`[CONSEILLERS] Une erreur est survenue lors de l'envoi des emails sur le partage des résultats PIX aux candidats : ` +
`[CONSEILLERS] Une erreur est survenue lors de l'envoi des emails sur le partage des résultats PIX aux candidats : ${err}`

2021-05-22 21:34 UTC, jystervinou commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +  return reg;
Je vois ça un peu tard, mais va voir toutes les dernières modifs que j'ai faites cette semaine sur l'import PIX, ce code n'est pas la dernière version. idem pour ci-dessous.
Le nouveau est bien plus efficace à matcher les comptes.

2021-05-22 21:34 UTC, jystervinou requested changes
Cf mes commentaires

2021-05-24 07:36 UTC, MorganP-projects commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +  return reg;
Ok je vais me mettre à jour :)

2021-05-24 14:45 UTC, squirrion commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +          logger.info(`KO1;${match.nom};${match.prenom};${pix.nom};${pix.prenom};${pix.id}`);
@MorganP-projects du coup normal qu'on push pas l'id ici comme userPix trouvé avec l'idPG ?

2021-05-24 14:50 UTC, squirrion commented on src/tools/admin/conseillers/candidatPixEnAttente/candidatPixEnAttente.js
> +          logger.info(`KO1;${match.nom};${match.prenom};${pix.nom};${pix.prenom};${pix.id}`);
@MorganP-projects OK vu idPG plus utilisable pour Pix (décalage...)

2021-05-24 14:50 UTC, squirrion approved these changes

2021-05-25 09:00 UTC, merged

2021-05-25 09:23 UTC, jystervinou reviewed
OK