Supprime la colorisation des lignes pour le moment, fait planter Excel
anct-cnum/api-conseiller-numerique pull request #277
Opened 2021-07-09 19:40 UTC by jystervinou

2021-07-12 10:13 UTC, loicguillois requested changes
pas mal d'erreur de lint

2021-07-12 10:13 UTC, loicguillois commented on src/tools/coselec/create-consolidated-excel.js
>        for (let j = 1; j < 32; j++) {
lint

2021-07-22 18:42 UTC, jystervinou commented
Fixed

2021-07-23 18:22 UTC, squirrion approved these changes

2021-07-26 15:32 UTC, merged