Ajout de l'exception dans le log
anct-cnum/api-conseiller-numerique pull request #278
Opened 2021-07-09 19:40 UTC by jystervinou

2021-07-12 10:14 UTC, loicguillois commented on src/services/siret/siret.class.js
> +      return new NotFound('SIRET not found' + err);
pourquoi faire ? c'est potentiellement une faille de sécurité. si c'est pour du débug il faut utiliser les logs

2021-07-22 18:35 UTC, jystervinou commented on src/services/siret/siret.class.js
> +      return new NotFound('SIRET not found' + err);
pour le loguer justement, on l'utilise que dans un script non ?

(c'est pour connaitre la raison de l'invalidité du SIRET)

2021-08-05 09:42 UTC, loicguillois requested changes

2021-08-05 09:42 UTC, loicguillois commented on src/services/siret/siret.class.js
> +      return new NotFound('SIRET not found' + err);
ce n'est du log. eturn new NotFound(...) renvoi l'erreur interne de l'application directement à l'utilisateur, ce qui est une mauvaise pratique. il faut utiliser le logger et sentry.

2021-08-25 13:56 UTC, closed without merging