Autre PR suite à l'erreur Sentry
anct-cnum/api-conseiller-numerique pull request #305
Opened 2021-07-21 15:05 UTC by Ornella452

…n de token

2021-07-21 15:27 UTC, loicguillois commented on src/services/users/users.class.js
> +        res.status(400).send(new BadRequest('La clé mailAModifier est undefined', {
ajoutes log.error et sentry

2021-07-22 08:09 UTC, loicguillois requested changes

2021-07-22 08:10 UTC, loicguillois commented on src/services/users/users.class.js
> +        await this.patch(userInfo._id, { $set: { token: uuidv4() } });
il n'y a aucun intérêt à faire 3 requêtes, regrouges tout dans une seule

2021-07-22 08:10 UTC, loicguillois commented on src/services/users/users.class.js
> +        app.get('sentry').captureException(`La clé mailAModifier est ${userInfo.mailAModifier}`);
pas utile, laisses juste le logger

2021-07-22 08:11 UTC, loicguillois commented on src/services/users/users.class.js
> +          app.get('sentry').captureException(`Erreur: l'email ${nouveauEmail}  est déjà utilisé par une autre structure`);
pas utile

2021-07-22 08:11 UTC, loicguillois commented on src/services/users/users.class.js
>            await message.render(user.data[0]);
l'appel de render ne sert à rien

2021-07-22 08:12 UTC, loicguillois commented on src/services/users/users.class.js
>              await message.render(user.data[0]);
appel de render ne sert à rien

2021-07-22 08:12 UTC, loicguillois commented on src/services/users/users.class.js
>              const user = await this.find({ query: { _id: idUser } });
utilises findOne quand tu veux en récupérer un seul

2021-07-22 08:13 UTC, loicguillois commented on src/services/users/users.class.js
>            const user = await this.find({ query: { _id: idUser } });
utilises findOne

2021-07-22 08:49 UTC, Ornella452 commented on src/services/users/users.class.js
>            await message.render(user.data[0]);
yes, tu as raison je ne l'utilise pas

2021-07-22 12:08 UTC, squirrion commented on src/services/users/users.class.js
> +        res.status(400).send(new BadRequest('La clé mailAModifier est undefined', {
@Ornella452 Tu peux rester en français je pense : le nouveau mail n'est pas renseignée

2021-07-22 12:09 UTC, squirrion commented on src/services/users/users.class.js
> +          logger.error(`Erreur: l'email ${nouveauEmail} est déjà utilisé par une autre structure`);
@Ornella452 Rajouter le Sentry

2021-07-22 12:10 UTC, squirrion commented on src/services/users/users.class.js
> +          logger.error(`Erreur: l'email ${nouveauEmail} est déjà utilisé par une autre structure`);
ah non tu sors en conflit au temps pour moi

2021-07-23 08:51 UTC, loicguillois commented on src/services/users/users.class.js
> +        logger.error(`Le token inconnue dans la DB: ${token}`);
`Token inconnu: ${token}` (c'est forcément en base de données, info inutile)

2021-07-23 08:51 UTC, loicguillois commented on src/services/users/users.class.js
> +        logger.error(`Erreur BD: ${err}`);
aucune plus value, logger.error(err)

2021-07-23 08:52 UTC, loicguillois commented on src/services/users/users.class.js
> +        logger.error(`Erreur BD: ${err}`);
aucune plus value, logger.error(err)

2021-07-23 08:53 UTC, loicguillois commented on src/services/users/users.class.js
> +        logger.error(`La clé mailAModifier est ${userInfo.mailAModifier}`);
inutile à supprimer

2021-07-23 08:54 UTC, loicguillois commented on src/services/users/users.class.js
> +          await this.patch(idUser, { $set: { token: uuidv4() } });
à faire en même temps que la ligne 192

2021-07-23 08:55 UTC, loicguillois commented on src/services/users/users.class.js
> +          logger.error(`Erreur : ${error}`);
aucun intérêt. logger.error(error)

2021-07-23 08:59 UTC, Ornella452 commented on src/services/users/users.class.js
> +          await this.patch(idUser, { $set: { token: uuidv4() } });
Je pense qua ça posera problème car sinon le `token` sera plus bon du coup lien invalide non ?

2021-07-23 09:10 UTC, Ornella452 commented on src/services/users/users.class.js
> +          await this.patch(idUser, { $set: { token: uuidv4() } });
ha ok je viens de comprendre , tu veux dire la ligne 192 =>  je le rapporte dans la ligne 184

2021-07-23 15:42 UTC, loicguillois approved these changes

2021-07-23 18:23 UTC, squirrion approved these changes

2021-07-23 20:48 UTC, merged