Simplification de la fonction createSexeAge
anct-cnum/api-conseiller-numerique pull request #324
Opened 2021-08-02 15:20 UTC by MorganP-projects

2021-08-02 15:28 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +
@MorganP-projects OK ! Faudrait vérifier le  rôle conseiller ou candidat => partir en 403 sinon

2021-08-03 07:55 UTC, squirrion approved these changes

2021-08-04 08:38 UTC, loicguillois requested changes

2021-08-04 08:38 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      const dateDeNaissance = req.body.dateDeNaissance;
c'est bien une date ?

2021-08-04 08:57 UTC, MorganP-projects commented on src/services/conseillers/conseillers.class.js
> +      const dateDeNaissance = req.body.dateDeNaissance;
Oui c'est une date

2021-08-04 09:17 UTC, jystervinou commented on src/services/conseillers/conseillers.class.js
> +        await this.patch(new ObjectId(user.entity.oid),
@loicguillois tu n'avais pas eu des problèmes avec patch ? @MorganP-projects

2021-08-05 10:02 UTC, MorganP-projects commented on src/services/conseillers/conseillers.class.js
> +      const dateDeNaissance = req.body.dateDeNaissance;
On a un champs ISODate en base

2021-08-05 14:18 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +        await this.patch(new ObjectId(user.entity.oid),
oui mais quand j'avais de multiples patch qui se marchait dessus (traitement asynchrone ...) là c'est ok

2021-08-05 14:18 UTC, loicguillois approved these changes

2021-08-05 14:20 UTC, merged