Mise à jour Script pour désactivé un candidat
anct-cnum/api-conseiller-numerique pull request #371
Opened 2021-08-18 13:38 UTC by Ornella452

Ticket Trello => https://trello.com/c/HvG4GdHr

2021-08-18 13:42 UTC, squirrion commented
@Ornella452 Vu ok, à confirmer avec @loicguillois

2021-08-23 07:54 UTC, loicguillois requested changes

2021-08-23 07:54 UTC, loicguillois commented on src/tools/admin/conseillers/desactiver.js
> +  program.option('--deleteTotal', 'Suppression total d\'un conseiller');
--supprimer

2021-08-23 07:54 UTC, loicguillois commented on src/tools/admin/conseillers/desactiver.js
> +    // SUPPRESSION TOTAL DU CONSEILLER avec la commande --deleteTotal
il faut vérifier que le conseiller n'a pas été invité à l'espace coop et bloquer dans ce cas

2021-08-23 08:20 UTC, Ornella452 commented on src/tools/admin/conseillers/desactiver.js
> +    // SUPPRESSION TOTAL DU CONSEILLER avec la commande --deleteTotal
Comment vérifier que la personne à été invité ?

Faut -il que je fasse une vérification dans `conseillers` , si `userCreated` est égale à true , alors je vérifie dans la collection `users` et si son roles est égale à "conseiller" alors échec ?!

2021-08-23 12:28 UTC, squirrion commented on src/tools/admin/conseillers/desactiver.js
> +        exit(`le conseiller: ${conseiller.nom} ${conseiller.prenom} avec l'idPG : ${conseiller.idPG} déjà invité à lespace coop`);
@Ornella452 Ok donc là ce sera un scirpt à part c'est ça ?

2021-08-23 12:29 UTC, squirrion commented on src/tools/admin/conseillers/desactiver.js
> +    logger.info(`Conseiller ${conseiller.nom} ${conseiller.prenom} avec l'id : ${id} est totalement supprimer`);
@Ornella452 supprimé

2021-08-23 12:30 UTC, Ornella452 commented on src/tools/admin/conseillers/desactiver.js
> +        exit(`le conseiller: ${conseiller.nom} ${conseiller.prenom} avec l'idPG : ${conseiller.idPG} déjà invité à lespace coop`);
oui et je pense que ça sera lié à ton script non ?

2021-08-23 12:31 UTC, squirrion commented on src/tools/admin/conseillers/desactiver.js
> +        exit(`le conseiller: ${conseiller.nom} ${conseiller.prenom} avec l'idPG : ${conseiller.idPG} déjà invité à lespace coop`);
ah oui tu as raison !

2021-08-23 12:31 UTC, squirrion commented on src/tools/admin/conseillers/desactiver.js
> +        exit(`le conseiller: ${conseiller.nom} ${conseiller.prenom} avec l'idPG : ${conseiller.idPG} déjà invité à lespace coop`);
mais je supprime pas le conseiller par contre (ca maj le statut en rupture)

2021-08-23 12:37 UTC, Ornella452 commented on src/tools/admin/conseillers/desactiver.js
> +        exit(`le conseiller: ${conseiller.nom} ${conseiller.prenom} avec l'idPG : ${conseiller.idPG} déjà invité à lespace coop`);
ha ok,  donc faudrait voir pour comment gérer ce cas là alors , commande en plus ?!

2021-08-23 12:44 UTC, loicguillois commented on src/tools/admin/conseillers/desactiver.js
> +    // SUPPRESSION TOTAL DU CONSEILLER avec la commande --deleteTotal
oui

2021-08-23 13:00 UTC, Ornella452 commented on src/tools/admin/conseillers/desactiver.js
> +    // SUPPRESSION TOTAL DU CONSEILLER avec la commande --deleteTotal
yes c'est fait alors 👍

2021-08-25 13:18 UTC, loicguillois approved these changes

2021-08-25 14:42 UTC, merged