WIP : Supprimer un candidat
anct-cnum/api-conseiller-numerique pull request #458
Opened 2021-09-24 09:14 UTC by Ornella452

2021-09-24 17:58 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +const { ObjectId, ObjectID } = require('mongodb');
@Ornella452 2 ObjectIds :)

2021-09-24 17:58 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +      //Pour vérifier que il n'est pas était validé ou recruté dans une quelconque structure
@Ornella452 n' pas été

2021-09-24 18:01 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +          'roles': { $elemMatch: { $eq: ['conseiller'] }
@Ornella452 pas besoin du $elematch vu qu'on vérifie un seul élément

2021-09-24 18:02 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        res.status(409).send(new Conflict(`Conseiller à un compte Espace coop`, {
@Ornella452 a un compte sans accent

2021-09-24 18:03 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        DELETE FROM djapp_matching WHERE coach_id = $1`,
@Ornella452 ca supprime quoi ici coté PG ?

2021-09-24 18:04 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +      res.send({ suppressionSuccess: true });
@Ornella452 ok ou deleteSuccess si tout en anglais

2021-09-24 18:06 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +const { ObjectId, ObjectID } = require('mongodb');
je sais pas si c'est normal

2021-09-24 18:22 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        res.status(409).send(new Conflict(`Conseiller à un statut particulier chez ${verifStatut.length} stuctures`, {
@Ornella452 passer le statut

2021-09-24 18:37 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +
@Ornella452 Il faudra traiter les doublons également (suppression partout conseillers / users /  misesEnRelation dans Mongo et conseiller dans PG en checkant si pas de statut particulier sur un des doublons

2021-09-24 22:56 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +const { ObjectId, ObjectID } = require('mongodb');
ça s'est importer automatiquement le ObjectID ... je vais garder seulement celui de base (ça fait la même chose je pense)

2021-09-24 23:00 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        DELETE FROM djapp_matching WHERE coach_id = $1`,
alors ça supprimer dans la table djapp_matching , car quand je supprime dans la table djapp_coach , il y a un conflit et PG n'aime pas , je me rappelle plus du nom de l'erreur exacte , mais en gros il faut le supprimer coter djapp_matching

2021-09-24 23:02 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        res.status(409).send(new Conflict(`Conseiller à un statut particulier chez ${verifStatut.length} stuctures`, {
Aurais tu un wording mieux que ce que j'ai mis , car il serre d'affichage en cas d'erreur ?!

2021-09-24 23:15 UTC, jystervinou commented
Il faut reparler lundi des suppressions/anonymisations avec Loïc. cc @squirrion @loicguillois

2021-09-25 00:21 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        DELETE FROM djapp_matching WHERE coach_id = $1`,
~ ça s'appelle une "contraint"

2021-09-27 07:12 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        res.status(409).send(new Conflict(`Conseiller à un statut particulier chez ${verifStatut.length} stuctures`, {
Suppression impossible : le conseiller est en statut ${conseiller.statut} avec la structure {$structure.nom} et tu peux effectivement laisser le id passé en paramètre également

2021-09-28 05:01 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +      const { _id, idPG } = conseiller.data[0];
@Ornella452 je pense qu'il faut que tu mettes cette déstructuration après la condition d'en-dessous car sinon ca va partir en erreur (cannot desctruct null object)

2021-09-28 05:06 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +          actionUser: 'admin',
@Ornella452 je pense que cette donnée en dure va plutôt dépendre du role user (admin ou le candidat lui même)

2021-09-29 14:38 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +          //Pour vérifier que il n'a pas été validé ou recruté dans une quelconque structure
@Ornella452 qu'il

2021-09-29 14:39 UTC, marc-gavanier approved these changes

2021-09-29 14:42 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +                'statut': { $in: ['finalisee', 'recrutee'] }
@Ornella452 La requete ici fait doublon non ? Car tu as totues les infos dans verifStatut

2021-09-29 14:44 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            const messageSiret = !structure?.siret ? '' : `, SIRET : ${structure?.siret}`;
@Ornella452 + simple => structure?.siret ?? `, SIRET : ${structure?.siret}`

2021-09-29 14:46 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            const messageSiret = !structure?.siret ? '' : `, SIRET : ${structure?.siret}`;
@Ornella452 + simple => tu fais  `structure?.siret ?? 'non renseigné'` et dans le message tu ajoutes la partie texte siret :

2021-09-29 14:46 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +                'statut': { $in: ['finalisee', 'recrutee'] }
faudrait il que je fasse verifStatut[0].statut ? à la place de toute la requête ?

2021-09-29 14:50 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +                'statut': { $in: ['finalisee', 'recrutee'] }
Ouep tu peux mais donc tu auras tjrs le premier résultat - ce qui suffit je pense mais ca veut dire que tu aurais pu faire un findOne directement sur le verifStatut directement ? car si un résultat c'est que faut pas supprimer

2021-09-29 14:51 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            // eslint-disable-next-line max-len
@Ornella452 Vraiment besoin de ce disable eslint ici (j'ai pas l'impression) ?

2021-09-29 14:53 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            res.status(409).send(new Conflict(`Le conseiller ${messageDoublonCoop} à un compte COOP d'activer`, {
@Ornella452 a un compte COOP

2021-09-29 14:57 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +          const verifCompteUser = await db.collection('users').find(
yes je vais faire ça !

2021-09-29 14:58 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            const conseillerSupprimer = profil;
@Ornella452 Pour info tu peux le faire avec la déstructuration :
const data = { a: 1, b: 2, c: 3 };
const { a, ...rest } = data;
console.log(rest); // { b: 2, c: 3 }

2021-09-29 14:59 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +                role: 'admin',
@Ornella452 humm à confirmer mais du coup on pourrait pas passer le req.body.actionUser ? car le isAdmin pourrait être un id d'un candidat dans le futur

2021-09-29 15:00 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +              objAnonyme.actionUser = req.body.actionUser;
@Ornella452 Ah ok tu as dissocié

2021-09-29 15:14 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +            // eslint-disable-next-line max-len
yes pas besoin là , c'est qu'un moment j'avais mis tout mis sur une ligne avec les conditions du haut

2021-09-29 15:17 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +              objAnonyme.actionUser = req.body.actionUser;
oui c'est bien ça !

2021-09-29 15:21 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +                'statut': { $in: ['finalisee', 'recrutee'] }
un moment j'avais fais un findOne partout j'avais des problèmes de promesses ect... du coup j'ai garder la version qui fonctionne

2021-09-29 18:27 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            const { email, telephone, nom , prenom, ...conseillerSupprimer } = profil;
@Ornella452 Yes avec cette destructuration, il faut que tu ajoutes // eslint-disable-next-line no-unused-vars

2021-09-29 18:29 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +            const { email, telephone, nom , prenom, ...conseillerSupprimer } = profil;
et y a un petit espace en trop après nom

2021-09-29 19:04 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +            const { email, telephone, nom , prenom, ...conseillerSupprimer } = profil;
ha oui tu as l'oeil !

2021-09-30 07:13 UTC, squirrion approved these changes

2021-09-30 08:38 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +    app.delete('/conseillers/:id/candidat', async (req, res) => {
j'aurais tendance à mettre /conseillers/:id/candidature, à voir l'avis des autres

2021-09-30 08:49 UTC, loicguillois requested changes

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +          const verifStatut = await db.collection('misesEnRelation').find(
attention au nommage des variables, ici c'est un tabeau de `misesEnRelation`, pourquoi ne pas l'appeler simplement `misesEnRelations` ?

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            const verifStatutFinalisee = await db.collection('misesEnRelation').findOne(
idem, `misesEnRelationsFinalisees`

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            return;
je n'ai pas compris l'utilisation du `return`

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +          const verifCompteUser = await db.collection('users').countDocuments(
ici c'est un nombre de users, donc `usersCount`

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            return;
pas compris ce return non plus

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      let verifAutorisationSupprime = [];
à la lecture de ce nom de variable , je ne sais pas ce qu'il y a de dedans... c'est un tableau de quoi ?

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      let archiveConseillersSupprimes = [];
à la lecture de ce nom de variable , je ne sais pas ce qu'il y a de dedans... c'est un tableau de quoi ?

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            const { email, telephone, nom, prenom, ...conseillerSupprimer } = profil;
je mettrais simplement `conseiller` plutôt que `conseillerSupprimer`

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +                idAdmin: user._id
`userId` plutôt que `idAdmin` (pas forcément un admin vu qu'on stock le rôle)

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            logger.info(`Erreur DB candidatsSupprimes : ${error.message}`);
on log l'objet dans kibana (json) `logger.info(error)`

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      let suppressionTotal = [];
à la lecture de ce nom de variable , je ne sais pas ce qu'il y a de dedans... c'est un tableau de quoi ?

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            logger.info(`Erreur DB for delete matching PG Conseiller : ${error.message}`);
idem, on log l'objet json directement, pas de chaîne de caractère

2021-09-30 08:49 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +            logger.info(`Erreur DB for delete Mongo Conseiller : ${error.message}`);
log de l'objet json directement

2021-09-30 09:00 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +            return;
pour être sure qu'il s'arrête

2021-09-30 09:45 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +    app.delete('/conseillers/:id/candidat', async (req, res) => {
yes je suis d'accord : ca peut supprimer plusieurs doublons de candidat (candidature reste générique)

2021-09-30 12:08 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      verificationRoleAdmin(app, decode, NotAuthenticated, Forbidden, req, res);
await verificationRoleAdmin ?

2021-09-30 12:08 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      verificationCandidaturesRecrutee(email, id, Conflict, app, promises, res);
await verificationCandidaturesRecrutee ?

2021-09-30 12:21 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +      verificationRoleAdmin(app, decode, NotAuthenticated, Forbidden, req, res);
pour verificationRoleAdmin il y a pas de problème

2021-09-30 12:22 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +      verificationCandidaturesRecrutee(email, id, Conflict, app, promises, res);
Pour verificationCandidaturesRecrutee , en mettant le await l'erreur est celui ci maintenant =>`error: Unhandled Rejection at: Promise`

2021-09-30 21:35 UTC, loicguillois requested changes

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      let promises = [];
tu n'as pas besoin de déclarer `promises` à ce niveau

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +    promises = [];
tu n'as qu'une seule promesse, tu peux  déclarer une simple variable `let promise;`

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +        promises.push(new Promise(async resolve => {
`promise = new Promise(async resolve => {`

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +      await Promise.allSettled(promises);
`await promise;`

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +    promises = [];
même principe que plus haut

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +    promises = [];
même principe que plus haut

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +      await verificationCandidaturesRecrutee(email, id, app, promises, res);
pour chercher la petite bête, dans l'idéal il faudrait que chaque fonction retourne une promesse (qui peut être `resolve()` ou `reject(reason)`) et utilisé le mot clef `.then()` pour enchainer l'appel de tes trois fonctions en cascade. Ensuite tu peux avoir le `.catch()` à la fin pour gérer les erreurs. https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

les fonctions ne devraient pas faire le retour HTTP car le contrôleur est ici et non pas dans le fichier séparé. Egalement, tu ne dois pas passer les requêtes directement aux fonctions mais les valeurs qui sont utilisées donc pour `archiverLaSuppression` tu ne transmets pas `req`, mais le motif (`req.body.motif`)

ça ferait  quelque chose comme ça : 

```
verificationCandidaturesRecrutee(email, id, app).then(() => {
return archiverLaSuppression(email, user, app, req)
}).then(() => {
return suppressionTotalCandidat(email, app);
}).then(() => {
   res.send({ deleteSuccess: true });
}).catch(reason => {
  res.status(409).send(new Conflict(reason));
});
```

prends le temps de faire ces modifications, et ce sera vraiment du code propre ;)

2021-09-30 21:35 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +              objAnonyme.actionUser = req.body.actionUser;
c'est quoi l'autre cas ? y a quoi comme données dans `actionUser` ?

2021-10-01 09:32 UTC, Ornella452 commented on src/services/conseillers/conseillers.function.js
> +              objAnonyme.actionUser = req.body.actionUser;
pour ici si c'est un candidat

2021-10-01 12:03 UTC, squirrion commented on src/services/conseillers/conseillers.function.js
> +        promise = new Promise(async resolve => {
@Ornella452 A confirmer avec Loïc mais je crois que tu aurais pu ici laisser les promises avec le promises.all car ici tu es dans un forEach

2021-10-01 12:53 UTC, loicguillois requested changes

2021-10-01 12:53 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +        return res.status(500).send(new GeneralError('Une erreur est survenue lors de la suppression de la candidature, veuillez réessayer.').toJSON());
top comme ça !

2021-10-01 12:53 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +        promise = new Promise(async resolve => {
ah oui bien vu, ici du coup :

`promises.push(new Promise(async resolve => {`

2021-10-01 12:53 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +    let promise;
du coup `let promises = [];`

2021-10-01 12:53 UTC, loicguillois commented on src/services/conseillers/conseillers.function.js
> +      await promise;
`await promises.all(promises)`

2021-10-01 13:34 UTC, loicguillois approved these changes

2021-10-05 12:14 UTC, MorganP-projects approved these changes

2021-10-05 12:17 UTC, Ornella452 commented on src/services/conseillers/conseillers.function.js
> +const verificationRoleAdmin = async (userAuthentifier, db, decode, req, res) => {
@squirrion comment a ton avis on aurais gérer ça ? car pour la fonctionnalité pour le moment c'est que admin qui est autoriser

2021-10-05 12:27 UTC, squirrion commented on src/services/conseillers/conseillers.function.js
> +const verificationRoleAdmin = async (userAuthentifier, db, decode, req, res) => {
@Ornella452 Ouep tu peux laisser comme ça pour le moment. Si on voulait faire une fonction générique, on aurait pu passer  le role ou les roles à vérifier en paramètre de la fonction (fonction réutilisable pour une vérif de role)

2021-10-05 15:09 UTC, Ornella452 commented on src/services/conseillers/conseillers.function.js
> +const verificationRoleAdmin = async (userAuthentifier, db, decode, req, res) => {
merci seb , changement fait !

2021-10-05 15:13 UTC, squirrion approved these changes

2021-10-05 15:50 UTC, merged