Script pour changer l'email perso d'un conseiller
anct-cnum/api-conseiller-numerique pull request #478
Opened 2021-10-12 09:43 UTC by Ornella452

2021-10-12 09:58 UTC, jystervinou commented on src/tools/admin/conseillers/change-email-perso.js
> +      });
et la table users ? champ "name"

2021-10-12 10:02 UTC, loicguillois requested changes
il ne faut pas créer de nouveau script

2021-10-12 12:10 UTC, loicguillois commented
> il ne faut pas créer de nouveau script

OK vu

2021-10-12 12:12 UTC, loicguillois commented on src/tools/admin/conseillers/change-email-perso.js
> +    exit('Paramètres invalides. Veuillez un type : candidat ou conseiller');
typo

2021-10-12 12:12 UTC, loicguillois commented on src/tools/admin/conseillers/change-email-perso.js
> +    if (role !== type) {
attention... il faut faire la vérification beaucoup plus tôt car là la requête dans Postgresql sera déjà passée...

2021-10-13 09:18 UTC, Ornella452 commented on src/tools/admin/conseillers/change-email-perso.js
> +      });
@jystervinou je n'est pas compris la question

2021-10-13 09:41 UTC, squirrion commented on src/tools/admin/conseillers/change-email-perso.js
> +  program.option('-t, --type <type>', `type: candidat ou un conseiller`);
@Ornella452 chipotage  candidat ou conseiller directement

2021-10-13 09:54 UTC, loicguillois commented on src/tools/admin/conseillers/change-email-perso.js
> +      });
@jystervinou c'est ligne 54

2021-10-13 13:10 UTC, merged