Invit Espace candidat
anct-cnum/api-conseiller-numerique pull request #543
Opened 2021-11-08 16:37 UTC by Ornella452

2021-11-08 17:46 UTC, squirrion commented on src/services/conseillers/conseillers.function.js
> +const { NotFound, Conflict, NotAuthenticated, Forbidden, GeneralError } = require('@feathersjs/errors');
@Ornella452 lint

2021-11-08 18:11 UTC, squirrion requested changes

2021-11-08 18:11 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        logger.error(error);
@Ornella452 Si erreur on set userCreationError: true ?

2021-11-09 10:18 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        logger.error(error);
yes bien vu !

2021-11-09 10:20 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        logger.error(error);
@squirrion  mais pas ici mais plus tôt ligne 520

2021-11-09 17:00 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +            createdAt: new Date(),
je n'avais pas du tout penser de cette façons, merci !

2021-11-09 17:21 UTC, loicguillois commented on src/services/conseillers/conseillers.class.js
> +          res.status(409).send(new Conflict(`${conseiller.prenom} ${conseiller.nom} est déjà recrutée donc a un compte COOP existant`));
déjà recruté

2021-11-09 19:31 UTC, squirrion commented on src/services/conseillers/conseillers.class.js
> +        app.get('sentry').captureException(error);
@Ornella452 j'ai un doute error.message ?

2021-11-10 12:42 UTC, Ornella452 commented on src/services/conseillers/conseillers.class.js
> +        app.get('sentry').captureException(error);
vu

2021-11-10 12:50 UTC, loicguillois approved these changes

2021-11-10 12:53 UTC, marc-gavanier approved these changes

2021-11-10 13:16 UTC, merged