WIP: Evolution du script out coop
anct-cnum/api-conseiller-numerique pull request #644
Opened 2021-12-27 14:43 UTC by Ornella452

2021-12-27 15:43 UTC, loicguillois requested changes

2021-12-27 15:43 UTC, loicguillois commented on src/tools/admin/conseillers/import-recrutes.js
> +            logger.error(`La date indiqué dans le fichier:${dateFinFormation} est le même que celui en base:${dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY')} pour le conseiller avec
`date indiquée`

2021-12-27 15:43 UTC, loicguillois commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY') === dayjs(dateFinFormation).format('DD/MM/YYYY')) && (idPGConseiller === conseillerOriginal.idPG)) {
pour que ce soit plus lisible, utilise dayjs plus haut, juste après la ligne 75

`dateFinFormation = dayjs(dateFinFormation).format('DD/MM/YYYY')`

2021-12-27 15:43 UTC, loicguillois commented on src/tools/admin/conseillers/import-recrutes.js
> +          const dateFinFormation = conseiller['Date de fin de formation'].replace(/^(.{2})(.{1})(.{2})(.{1})(.{4})$/, '$5-$3-$1');
utilises `let`

2021-12-27 15:43 UTC, loicguillois commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY') === dayjs(dateFinFormation).format('DD/MM/YYYY')) && (idPGConseiller === conseillerOriginal.idPG)) {
mets `(dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY')` dans une variable plus haut également:

`const dateFinFormationConseiller = (dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY')`

2021-12-27 15:43 UTC, loicguillois commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY') === dayjs(dateFinFormation).format('DD/MM/YYYY')) && (idPGConseiller === conseillerOriginal.idPG)) {
comme ça tu peux faire ici : `dateFinFormation == dateFinFormationConseiller`

2021-12-28 20:53 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +          let dateFinFormation = conseiller['Date de fin de formation'].replace(/^(.{2})(.{1})(.{2})(.{1})(.{4})$/, '$5-$3-$1');
@Ornella452 Tu peux repasser en const car il ne faut pas faire dateFinFormation = dayjs(dateFinFormation).format('DD/MM/YYYY'); sinon l'enregistrement en base en type date ne fonctionnera pas dans Mongo

2021-12-28 20:58 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dateFinFormationConseiller === dateFinFormation) && (idPGConseiller === conseillerOriginal.idPG)) {
@Ornella452 Tu peux supprimer ce nouveau bloc. L'évolution à faire est dans le `if (alreadyRecruted > 0)`
=> Si déjà recruté, on verifie que dateFinFormationConseiller et dateFinFormation sont identiques, :
Si c'est le cas, on ne fait rien
Si c'est pas le cas, on met à jour  les 2 dates de formation (updateOne sur le conseiller recruté et updateMany des conseillerObj)

2021-12-28 20:59 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +          const dateFinFormationConseiller = dayjs(conseillerOriginal.dateFinFormation).format('DD/MM/YYYY');
@Ornella452 le + simple pour ne pas modifier dateFinFormation  est de mettre directement dateFinFormationConseiller  avec le format équivalent à dateFinFormation

2021-12-28 21:03 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dateFinFormationConseiller === dateFinFormation) && (idPGConseiller === conseillerOriginal.idPG)) {
Et au passage un petit logger info pour noter ceux qui ont eu une modification de date

2021-12-29 08:25 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +          } else if ((dateFinFormationConseiller === dateFinFormation) && (idPGConseiller === conseillerOriginal.idPG)) {
oooh c'était juste ça ! effectivement j'avais mal compris sur ce qu'il fallait faire !! 
je fais les modifs cette après midi 👍

2021-12-29 18:13 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +                dateFinFormation: dayjs(dateFinFormation, 'YYYY-MM-DD').toDate()
- tu peux en profiter pour maj la date de début également ici au as où
- remplacer dayjs(dateFinFormation, 'YYYY-MM-DD').toDate() par dateFinFormation

2021-12-29 18:16 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +              await db.collection('conseillers').updateOne({ _id: conseillerOriginal._id }, { $set: {
Déplacer le else if (!regexDateFormation.test(conseiller['Date de fin de formation']) || !regexDateFormation.test(conseiller['Date de départ en formation'])) en premier, ca évitera de maj des données non désirées

2021-12-29 18:17 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +              await db.collection('conseillers').updateOne({ _id: conseillerOriginal._id }, { $set: {
avant le if (alreadyRecruted > 0)

2021-12-30 08:11 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +              await db.collection('conseillers').updateOne({ _id: conseillerOriginal._id }, { $set: {
oui bien vue !

2021-12-30 10:45 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +                dateFinFormation: dayjs(dateFinFormation, 'YYYY-MM-DD').toDate()
pour le 2 èmes points `dateFinFormation` il fait simplement le format `2021-12-30` et pas comme ça `2021-11-09 23:00:00.000Z` du coup j'ai regardé en prod comment c'était et c'est bien comme ça `2021-11-09 23:00:00.000Z` pour la cohérence on laisse comme ça ?

2022-01-03 09:16 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +            if (((formatDate(conseillerOriginal.dateFinFormation) !== formatDate(dateFinFormation)) || (formatDate(conseillerOriginal.datePrisePoste) !== formatDate(datePrisePoste))) && (idPGConseill
@Ornella452 Vraiment besoin de la partie idPGConseiller === conseillerOriginal.idPG ?

2022-01-03 09:19 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +              await db.collection('misesEnRelation').updateOne({ 'conseiller.$id': conseillerOriginal._id, 'statut': 'finalisee' }, {
@Ornella452 Je pense que tu peux passer en updateMany sur 'conseiller.$id': conseillerOriginal._id non ?

2022-01-03 09:25 UTC, squirrion commented on src/tools/admin/conseillers/import-recrutes.js
> +              logger.info(`${loggerDateFin} ${loggerDateDebut} pour le conseiller avec l'id: ${idPGConseiller}`);
@Ornella452 Pas trop à rallonge le logger ici ? Est-ce qu'il faut pas dissocier les  loggers dateFin et dateDebut ?

2022-01-03 15:27 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +            if (((formatDate(conseillerOriginal.dateFinFormation) !== formatDate(dateFinFormation)) || (formatDate(conseillerOriginal.datePrisePoste) !== formatDate(datePrisePoste))) && (idPGConseill
@squirrion  non pas vraiment mais comme au début je regarder le ticket trello j'avais compris qu'il fallait aussi se baser sur  l'id  .. mal compris pour le coup ...

2022-01-03 15:30 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +              await db.collection('misesEnRelation').updateOne({ 'conseiller.$id': conseillerOriginal._id, 'statut': 'finalisee' }, {
yes tu as raison !

2022-01-03 15:37 UTC, Ornella452 commented on src/tools/admin/conseillers/import-recrutes.js
> +              logger.info(`${loggerDateFin} ${loggerDateDebut} pour le conseiller avec l'id: ${idPGConseiller}`);
j'avoue ça peut être un lonng logger si la date de début et la date fin n'est pas pareil en base ... veux tu le faire en 2 loggers distingue ?
si oui alors il faudrait une condition pour traiter cela car il faudrait pas un loggers vide : 

`
if (loggerDateFin !== '') {
logger.info(`${loggerDateFin} pour le conseiller avec l'id: ${idPGConseiller}`);
}
if (loggerDateDebut !== '') {
logger.info(`${loggerDateDebut} pour le conseiller avec l'id: ${idPGConseiller}`);
}
`

2022-01-03 15:57 UTC, squirrion approved these changes

2022-01-03 16:11 UTC, MorganP-projects approved these changes

2022-01-07 15:42 UTC, merged