MEP
anct-cnum/api-conseiller-numerique pull request #650
Opened 2021-12-29 16:10 UTC by Ornella452

2021-12-29 16:25 UTC, loicguillois commented
attention, on ne merge pas tant que les modifications sur metabase ne sont pas faites

2021-12-29 16:25 UTC, loicguillois requested changes
On attend

2022-01-06 10:24 UTC, marc-gavanier commented on src/tools/scripts/mailbox/fixErroredUsers.js
> +    await sleep(500);
Je ne vois pas où se situe l'appel qui présente un risque de surcharge de l'API Gandi

2022-01-13 09:55 UTC, loicguillois approved these changes

2022-01-13 09:57 UTC, merged