Ajout de la validation pour récupéré la donner du cra
anct-cnum/api-conseiller-numerique pull request #700
Opened 2022-02-02 08:33 UTC by Ornella452

2022-02-02 11:20 UTC, marc-gavanier approved these changes

2022-02-02 11:30 UTC, loicguillois approved these changes

2022-02-02 14:52 UTC, MorganP-projects approved these changes

2022-02-03 20:55 UTC, squirrion commented on src/services/cras/cras.hooks.js
> +          organisme: Joi.string().required().allow(null).error(new Error('L\'accompagnement est invalide'))
L\'organisme est invalide

2022-02-03 20:56 UTC, squirrion commented on src/services/cras/cras.hooks.js
> +          organisme: Joi.string().required().allow(null).error(new Error('L\'accompagnement est invalide'))
Et peut etre rajouter la liste des données valides si c'est possible comme ce qui est fait au-dessus

2022-02-03 20:57 UTC, squirrion requested changes
2 petits comms

2022-02-03 21:18 UTC, squirrion commented on src/services/cras/cras.hooks.js
> +          organisme: Joi.string().required().allow(null).error(new Error('L\'accompagnement est invalide'))
Nom de la PR à renommer

2022-02-09 08:17 UTC, squirrion commented
à voir si faudra ajuster les anciens CRAs pour mettre l'organisme à null (ou alors l'intégrer à un update de Morgan sur les anciens CRAs) car il me semble que ce sera à null si non renseigné c'est ca ?

2022-02-10 16:42 UTC, squirrion approved these changes

2022-02-14 09:58 UTC, merged