update npm dependencies
anct-cnum/api-conseiller-numerique pull request #753
Opened 2022-03-11 12:28 UTC by loicguillois

2022-03-11 13:06 UTC, MorganP-projects approved these changes

2022-03-11 13:14 UTC, marc-gavanier approved these changes

2022-03-11 15:23 UTC, squirrion requested changes
Clever tools ?

2022-03-11 15:28 UTC, squirrion commented on package.json
> +    "puppeteer": "13.5.1",
faudra faire un test de PDF

2022-03-11 16:27 UTC, loicguillois commented on package.json
> +    "clever-tools": "2.9.0",
bien vu, pas compris pourquoi il est revenu...

2022-03-14 08:22 UTC, squirrion approved these changes

2022-03-14 09:21 UTC, merged